

//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================


module MAXII_Power_Monitor(

	//////////// CLOCK //////////
	input 		          		MAX10_CLK1_24,
	//////////// LED //////////
	output		     	   	   MAX_WARN_LED,

	//////////// Power Monitor //////////
	output		          		PMONITOR_I2C_SCL,
	inout 		          		PMONITOR_I2C_SDA,
	
	//////////// PoweDown ///////////////
	output 				  		   SOC_SYS_PDN_n,
	/////////// Battery LED /////////////
	output 	[2:0]		   		BATTERY_LED	

);



SMC_POWER_MONITOR monitor(
	.MAX10_CLK1_24(MAX10_CLK1_24),
	.MAX_WARN_LED(MAX_WARN_LED),
	.PMONITOR_I2C_SCL(PMONITOR_I2C_SCL),
	.PMONITOR_I2C_SDA(PMONITOR_I2C_SDA),
	.SOC_SYS_PDN_n(SOC_SYS_PDN_n),
	.BATTERY_LED(BATTERY_LED[2:0])	
);


endmodule
